import { createServerClient } from '@supabase/ssr';
import { NextResponse } from 'next/server';

// Refreshes the Supabase session on every request and keeps unauthenticated
// users out of the app. Login and the auth callback stay open.
export async function middleware(request) {

  /* =====================================================================
     ONE ADDRESS: soberbook.app.
     ---------------------------------------------------------------------
     Aug 23. Ty: "we want an easy nice experience for new and old users."

     soberbook.vercel.app still answers, and anybody who was sent that
     link months ago still has it in a DM or a bio. It works, so nothing
     looks broken — it just isn't the address on the posters, the flyer
     QR or the domain we pay for. Two front doors is how you end up
     supporting two front doors.

     ⚠️ 307, NOT 308/301. A permanent redirect is cached by the browser
     more or less forever; if this ever needs undoing — a DNS problem on
     soberbook.app, say — everyone who hit it once is stuck on a rule we
     can no longer change. Temporary costs nothing here and stays
     reversible.

     🔴 /auth AND /reset ARE EXCLUDED, AND THAT IS THE IMPORTANT PART.
     Supabase puts the recovery token in the URL **fragment**
     (#access_token=…). A fragment is never sent to the server, so a
     server-side redirect SILENTLY DROPS IT — the link is spent, the
     token is gone, and the person is locked out with no explanation.
     Old reset emails were sent with a vercel.app redirect address and
     those links must keep working. See the note further down; this is
     the same trap from the other direction.
     ===================================================================== */
  const host = request.headers.get('host') || '';
  const path = request.nextUrl.pathname;
  const tokenPath = path.startsWith('/auth') || path.startsWith('/reset');

  if (host.endsWith('.vercel.app') && !tokenPath) {
    const to = new URL(path + request.nextUrl.search, 'https://soberbook.app');
    return NextResponse.redirect(to, 307);
  }

  let response = NextResponse.next({ request });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    {
      cookies: {
        getAll: () => request.cookies.getAll(),
        setAll: (list) => {
          list.forEach(({ name, value }) => request.cookies.set(name, value));
          response = NextResponse.next({ request });
          list.forEach(({ name, value, options }) => response.cookies.set(name, value, options));
        },
      },
    }
  );

  const { data: { user } } = await supabase.auth.getUser();

  /* ⚠️ /reset MUST BE OPEN, AND THIS IS NOT A CONVENIENCE — WITHOUT IT
     PASSWORD RESET CANNOT WORK AT ALL.

     Supabase puts the recovery token in the URL **fragment**
     (#access_token=…). A fragment is never sent to the server, so this
     middleware sees a person with no session and bounces them to
     /login — and the redirect throws the fragment away. The token is
     gone, the link is spent, and the person is back where they started
     with no idea why.

     The exchange has to happen in the browser, which means the page has
     to be allowed to load first. It is safe: arriving at /reset with no
     valid token gets you a form that can't do anything, because
     updateUser needs a session the token is the only way to obtain. */
  /* ⚠️ /privacy IS OPEN, and it has to be. Google Play and the App Store
     both require a privacy policy at a URL anyone can reach without an
     account — and putting the page that explains what we collect behind
     a sign-up form would be its own small joke. It contains no personal
     data; it's a document. */
  /* 🔴 /api/push/send IS OPEN TO THE MIDDLEWARE, AND IT MUST BE.

     Found by a live test at 12:09am: a real notification row fired the
     trigger, pg_net called the route, and got **405**. The route was fine
     — the middleware never let it arrive.

     ⭐ THE MECHANISM IS WORTH KNOWING. pg_net carries no cookies, so
     `!user` is true, so this file redirected it to /login — and
     NextResponse.redirect() defaults to **307, which PRESERVES the
     method**. A POST therefore landed on /login, which is a page and has
     no POST handler. Hence 405, from a route that was never touched.

     ⚠️ Every other redirect note in this file is about 307 being the
     RIGHT choice (it keeps the auth fragment alive). Here the same
     property is what broke it. The status code wasn't wrong; applying
     browser rules to a server-to-server call was.

     🔴 THIS OPENS NOTHING. /api/push/send authenticates itself with a
     shared secret generated by Postgres and stored in push_config, a
     table with no grants to anon or authenticated — and it answers 404,
     not 403, to anyone without it. It was never relying on this
     middleware for protection, which is exactly why it is safe to
     exclude and why nothing else here is being excluded with it.

     ⚠️ Do NOT widen this to '/api'. Other routes DO lean on the session
     that the middleware guarantees; opening them all would be a real
     hole opened for a one-route problem. */
  /* 🔴 /api/content/cron — SAME TRAP, SECOND VICTIM. Aug 27.

     The content feed had not refreshed in 64 HOURS. Two 7am runs came and
     went and wrote nothing. Vercel Cron is a server-to-server GET with no
     cookies, so `!user` was true, so this file redirected it to /login and
     the route was never reached. Green cron logs, silent no-op — the exact
     failure the route's own header warns about.

     ⚠️ THE LESSON, AND IT IS EMBARRASSING: the paragraph directly above
     describes this mechanism precisely, for pg_net, and the cron was built
     straight into it anyway. **Anything that calls us without a browser —
     pg_net, Vercel Cron, a webhook, a health check — has no cookies and
     dies here.** Check this list FIRST when adding one.

     🔴 THIS OPENS NOTHING NEW. The route carries no secret by design and
     never did: it is rate-limited by its own data (refuses if any source
     pulled within 6h), reads public RSS, and writes only rows it would
     have written anyway. Its protection was never this middleware — the
     middleware was only ever breaking it. See the route's own header for
     the full argument, including the line that matters: if it ever gains a
     side effect that isn't idempotent, it needs real auth that day. */
  /* ⚠️ TWO ADDED 31 AUG, BOTH FOR THE REASON THE PARAGRAPH ABOVE SPELLS OUT.
       /api/email/notify — poked by pg_cron through pg_net every five
         minutes. No browser, no cookies. Without this line it would
         redirect to /login forever and no email would ever be sent, with
         nothing in any log saying so. It carries its own shared secret
         (x-email-secret) and refuses without it, so this opens nothing.
       /unsub — the one-tap off switch in every notification email. 🔴 It
         MUST work for somebody who is not signed in; that is its entire
         purpose. The person most likely to want out is the person who
         does not want to open this app on the machine they are sitting
         at, and making them log in to leave would be its own small
         cruelty. Protected by an unguessable token that can only ever
         turn things OFF. */
  const open = ['/login', '/auth', '/reset', '/privacy', '/api/push/send', '/api/content/cron',
                '/api/email/notify', '/unsub'];
  const isOpen = open.some((p) => request.nextUrl.pathname.startsWith(p));

  /* 🔴 A STRANGER AT THE FRONT DOOR GETS THE PITCH, NOT A PASSWORD BOX.
     ---------------------------------------------------------------------
     Found Aug 18, the night the posters were made. Every poster and the
     flyer send people to soberbook.app — and a signed-out visitor was
     being redirected straight to /login, which says **"Welcome back —
     sign in to pick up where you left off."**

     To somebody who has never heard of Sober Book, that is a password
     box and a sentence implying they've already been here. Nothing on
     the screen says what this is or why they'd want it. Every scan of
     every poster would have landed there.

     ⚠️ REWRITE, NOT REDIRECT. A redirect would change the address bar to
     /home.html — ugly on a poster scan and it leaks an implementation
     detail. A rewrite serves the file while the URL stays soberbook.app,
     which is the address printed on the poster.

     ⭐ And the page served is Ty's approved landing page, byte for byte.
     It was not rebuilt, restyled or "improved" on the way through — only
     its links were made relative. He signed that design off on Aug 15
     and it is not mine to redraw. */
  /* ⚠️ Aug 23 — NOW REWRITES TO /login, NOT /home.html.
     ---------------------------------------------------------------------
     The note above is kept because the reasoning still holds: a stranger
     at the front door must not meet a bare password box. What changed is
     that /login IS the pitch now — one page carrying the sentence, the
     sign-in box and the make-an-account box together.

     🔴 home.html served the pitch and then handed people to /login, which
     said "Welcome back". People who loved the idea bounced off a password
     they'd never set and reported it as "the old version". Serving the
     pitch and the door as two pages is what created the gap; serving them
     as one closes it.

     ⚠️ Still a REWRITE, not a redirect — soberbook.app is the address on
     the posters and the flyer, and it has to stay in the address bar.

     ⚠️ public/home.html is deliberately left in place. It is Ty's approved
     long-form design and is still reachable directly; nothing links to it
     for now. Don't delete it. */
  if (!user && request.nextUrl.pathname === '/') {
    return NextResponse.rewrite(new URL('/login', request.url));
  }

  if (!user && !isOpen) {
    const url = request.nextUrl.clone();
    url.pathname = '/login';
    return NextResponse.redirect(url);
  }
  return response;
}

/* ⚠️ THE THREE INSTALL FILES HAVE TO BE PUBLIC, AND THEY WEREN'T.
   ---------------------------------------------------------------------
   Found the moment soberbook.app went live, Aug 18. The matcher already
   let images through, but not `manifest.webmanifest`, `sw.js` or
   `offline.html` — so a signed-OUT visitor asking for any of them got
   bounced to /login and received an HTML page where a manifest should
   be.

   That means a stranger could not install the app. At all. The browser
   needs the manifest and the service worker to offer "Add to Home
   Screen", and it could reach neither until you had an account.

   🔴 It was invisible on soberbook.vercel.app for a month because Ty
   was permanently signed in there — the files loaded fine for the one
   person who never needed them to. The new domain had no session
   cookie, which is the first time anything asked for these files as a
   stranger would. **A new domain is an accidental logged-out test of
   your entire app.**

   Safe to open: the manifest is a name, some colours and icon paths;
   sw.js is our own code with no secrets in it; offline.html is a static
   page. Nothing here reads a session or touches the database. */
/* 🔴 ONE UNBROKEN STRING. DO NOT SPLIT IT ACROSS LINES WITH `+`.
   ---------------------------------------------------------------------
   I wrote this as three concatenated strings the first time, purely so
   it would fit on a screen. It deployed, the build went green, and the
   fix did nothing.

   Next.js reads `matcher` by STATIC ANALYSIS at build time — it looks at
   the literal in the source, it does not run the file. `'a' + 'b'` is an
   expression, not a literal, so the config was unreadable and the
   middleware fell back to guarding everything, exactly as before.

   ⚠️ Nothing warned about this. No build error, no console message. The
   deployment was "Ready" and the behaviour was unchanged, which is the
   worst combination — it looks like your change was wrong when in fact
   your change was never read.

   ⭐ Same family as the two `app/` folders and the dropped `lib` folder:
   a silent no-op that reports success. When a change appears to have no
   effect, check whether it was READ before assuming it was wrong. */
export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico|manifest\\.webmanifest|sw\\.js|offline\\.html|home\\.html|.*\\.(?:svg|png|jpg|jpeg|gif|webp|webmanifest|ico)$).*)'],
};
