import { NextResponse } from 'next/server';
import { adminClient, adminConfigured } from '../../../../lib/supabase-admin';
import { sendMail, answeredEmail } from '../../../../lib/mail';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/* =====================================================================
   THE SECOND CHANNEL.  31 Aug.

   pg_cron pokes this every five minutes through pg_net (migration 0102).
   It asks the database who is owed an email, sends them, and marks them
   sent. It decides nothing — every rule about WHO gets mail lives in
   `email_pending()`, where it can be enforced rather than remembered.

   ---------------------------------------------------------------------
   ⚠️ THE SHAPE IS COPIED FROM /api/push/send DELIBERATELY. Same shared
   secret pattern, same admin client, same "the database holds the
   queue". Two channels that behave the same way are one thing to learn
   and one thing to debug. Where they differ, they differ on purpose:

     - push fires from a TRIGGER, instantly, because push is the "right
       now" channel;
     - email fires from a SWEEP, five minutes later, because email is
       the "you were away" channel. That delay is what stops us emailing
       somebody about a reply they are looking at in the app right now.

   🔴 THIS ROUTE IS IN middleware.js's `open` LIST. It has to be — pg_net
   arrives with no cookies, so without that it would redirect to /login
   every five minutes and send nothing, silently, forever. That is not a
   hypothetical: it happened to the content cron for 64 hours in August.
   The protection is the secret below, not the middleware.
   ===================================================================== */

export async function POST(req) {
  if (!adminConfigured()) {
    return NextResponse.json({ ok: false, error: 'admin not configured' }, { status: 500 });
  }
  const admin = adminClient();

  /* The shared secret was generated BY POSTGRES and lives in email_config,
     which grants nothing to anon or authenticated. The browser has never
     seen it and has no way to. */
  const { data: cfg } = await admin
    .from('email_config').select('secret').eq('id', 1).maybeSingle();
  const sent = req.headers.get('x-email-secret') || '';
  if (!cfg?.secret || sent !== cfg.secret) {
    /* ⚠️ 404, not 403. A 403 confirms the route exists and that a secret
       is the thing missing, which is a hint. */
    return NextResponse.json({ ok: false }, { status: 404 });
  }

  const { data: pending, error } = await admin.rpc('email_pending');
  if (error) {
    return NextResponse.json({ ok: false, error: error.message }, { status: 500 });
  }
  if (!pending || pending.length === 0) {
    return NextResponse.json({ ok: true, sent: 0, note: 'nothing owed' });
  }

  /* ⭐ ONE EMAIL PER PERSON PER SWEEP, NOT ONE PER NOTIFICATION.

     Three people answering your post inside five minutes is three rows.
     Three emails for that is the "eleven separate buzzes" problem the
     service worker already refuses with a single notification tag — and
     it is worse in a mailbox, where they stack up visibly and look like
     spam to both the reader and to Gmail.

     ⚠️ All of that person's rows still get marked sent, so the ones we
     folded in never come back around on the next sweep. */
  const firstPerPerson = new Map();
  const idsByEmail = new Map();
  for (const row of pending) {
    if (!firstPerPerson.has(row.email)) firstPerPerson.set(row.email, row);
    if (!idsByEmail.has(row.email)) idsByEmail.set(row.email, []);
    idsByEmail.get(row.email).push(row.notification_id);
  }

  let ok = 0;
  const failed = [];
  const marked = [];

  for (const [email, row] of firstPerPerson) {
    /* ⚠️ TWO DIFFERENT URLS, AND THEY ARE NOT INTERCHANGEABLE.

       The one a HUMAN clicks goes to a page that shows a button and
       changes nothing on load — because link scanners follow every URL
       in an email with a GET, and a GET that unsubscribes people means
       members get switched off by a robot that read their mail first.

       The one in the HEADER is the POST-only endpoint, because Gmail's
       and Outlook's own one-click unsubscribe button sends a POST
       (RFC 8058). A scanner's GET on it does nothing. */
    const pageUrl = `https://soberbook.app/unsub/${row.optout_token}`;
    const postUrl = `https://soberbook.app/api/unsub/${row.optout_token}`;
    const { subject, html, text } = answeredEmail({ optoutUrl: pageUrl, kind: row.kind });

    const res = await sendMail({
      to: email,
      subject,
      html,
      text,
      /* ⭐ One-click unsubscribe, the real one. Gmail and Outlook render
         their OWN "Unsubscribe" button next to the sender when these two
         headers are present, and — this is the part that matters —
         somebody who wants out uses that instead of clicking "report
         spam". A spam complaint damages the domain's reputation for
         every member; an unsubscribe costs us one person's email. */
      headers: {
        'List-Unsubscribe': `<${postUrl}>`,
        'List-Unsubscribe-Post': 'List-Unsubscribe=One-Click',
      },
    });

    if (res.ok) {
      ok += 1;
      marked.push(...idsByEmail.get(email));
    } else {
      /* ⚠️ NOT marked sent. A failed send has to come back around on the
         next sweep, or a transient Resend blip silently eats somebody's
         only signal that a person answered them. The 3-day window in
         email_pending() stops a permanently bad address retrying
         forever. */
      failed.push({ error: res.error });
    }
  }

  if (marked.length) {
    await admin.rpc('email_mark_sent', { p_ids: marked });
  }

  /* ⚠️ No addresses and no ids in the response. This is a log line that
     lands in Vercel's output, and an address there is a member's identity
     sitting in a third party's log store. Counts only — the same rule
     /admin/numbers lives by. */
  return NextResponse.json({
    ok: true,
    sent: ok,
    folded: marked.length - ok,
    failed: failed.length,
  });
}

/* ⚠️ GET is the dry run and sends nothing. Same convention as the
   content pull. 🔴 And the same trap it left behind: NEVER point a
   scheduler at GET and assume it is working — /api/content/cron exists
   as a separate route precisely because a cron aimed at a dry run logs
   green every time and does nothing. */
export async function GET(req) {
  if (!adminConfigured()) {
    return NextResponse.json({ ok: false, error: 'admin not configured' }, { status: 500 });
  }
  const admin = adminClient();

  /* 🔴 THE SECRET IS REQUIRED HERE TOO, and leaving it off was a hole I
     opened an hour ago. This route sits in middleware's `open` list, so
     "it's only a dry run" meant anybody on the internet could read how
     many notification emails were pending and how many people were owed
     one. No names — but counts ARE the security model on /admin/numbers
     for exactly this reason: at 125 members, "3 people are owed an
     email right now" is a live activity readout of a recovery community
     to anyone who asks. */
  const { data: cfg } = await admin
    .from('email_config').select('secret').eq('id', 1).maybeSingle();
  if (!cfg?.secret || (req.headers.get('x-email-secret') || '') !== cfg.secret) {
    return NextResponse.json({ ok: false }, { status: 404 });
  }

  const { data, error } = await admin.rpc('email_pending');
  if (error) return NextResponse.json({ ok: false, error: error.message }, { status: 500 });
  return NextResponse.json({
    ok: true,
    dryRun: true,
    owed: (data || []).length,
    people: new Set((data || []).map((r) => r.email)).size,
    hasKey: Boolean(process.env.RESEND_API_KEY),
  });
}
