import { NextResponse } from 'next/server';
import { adminClient, adminConfigured } from '../../../../lib/supabase-admin';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/* =====================================================================
   THE DATABASE CALLS THIS  (0073 / 0074).

   ⭐ WHY THE DATABASE AND NOT THE APP.

   Notifications are written by TRIGGERS (0025 reply, 0025 message, 0067
   tag). Nothing in Node ever learns one happened, so no ordinary route
   could send the push — it doesn't know there's anything to send. And
   polling on a schedule was ruled out on evidence: the one Vercel cron
   this project has has never fired, three slots missed.

   So `push_on_notification()` fires pg_net at this route the instant the
   row lands. pg_net is asynchronous, so a slow push service can never
   delay somebody posting a reply.

   ---------------------------------------------------------------------
   🔴 THE REQUEST BODY IS ONE UUID.

   No handle, no words, no kind. This route looks everything else up
   itself — and even then, the only thing it puts in the push payload is a
   destination path. The words on the phone are constants inside sw.js.

   ⚠️ Two locks, deliberately: to leak a name onto a lock screen somebody
   would have to change the payload here AND the text in the service
   worker. Neither one alone does it.
   ===================================================================== */

export async function POST(req) {
  if (!adminConfigured()) {
    return NextResponse.json({ error: 'not configured' }, { status: 500 });
  }

  const admin = adminClient();

  /* The shared secret was generated BY POSTGRES and lives in push_config,
     which has no grants to anon or authenticated. ⚠️ Without it, anyone
     who guessed this route could make a member's phone buzz at 3am —
     silent payload or not, that is harassment, and at 2am to somebody in
     early recovery it is worse than that. */
  const { data: cfg } = await admin
    .from('push_config').select('secret').eq('id', 1).maybeSingle();
  const sent = req.headers.get('x-push-secret') || '';
  if (!cfg?.secret || sent !== cfg.secret) {
    /* 404 rather than 401 — an unauthorised caller learns nothing about
       whether this route exists. Same shape as /api/content/hide. */
    return NextResponse.json({ error: 'Not found.' }, { status: 404 });
  }

  let id;
  try { ({ id } = await req.json()); } catch { id = null; }
  if (!id) return NextResponse.json({ error: 'no id' }, { status: 400 });

  /* 🔴 CLAIM IT FIRST, THEN SEND. claim_push() stamps pushed_at in a
     conditional UPDATE, so two calls racing produce exactly one winner —
     the database does the locking, not this file. An empty result means
     somebody already told this phone, and we stop. */
  const { data: claimed, error: claimErr } = await admin.rpc('claim_push', { p_id: id });
  if (claimErr) return NextResponse.json({ error: claimErr.message }, { status: 500 });
  const n = Array.isArray(claimed) ? claimed[0] : claimed;
  if (!n) return NextResponse.json({ ok: true, skipped: 'already sent' });

  /* Where tapping it should land. ⚠️ A PATH ONLY, and the service worker
     re-checks the shape before using it. */
  const to = n.kind === 'message' ? (n.thread_id ? `/chat/${n.thread_id}` : '/chat')
           : n.kind === 'friend'  ? '/friends'
           : '/wall';

  const { data: subs } = await admin
    .from('push_subscriptions')
    .select('id, endpoint, p256dh, auth, failures')
    .eq('user_id', n.user_id);

  if (!subs?.length) return NextResponse.json({ ok: true, devices: 0 });

  const webpush = (await import('web-push')).default;
  webpush.setVapidDetails(
    process.env.VAPID_SUBJECT || 'mailto:ty.howell2007@gmail.com',
    process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY,
    process.env.VAPID_PRIVATE_KEY
  );

  const payload = JSON.stringify({ to });
  const dead = [];
  let ok = 0;

  await Promise.all(subs.map(async (s) => {
    try {
      await webpush.sendNotification(
        { endpoint: s.endpoint, keys: { p256dh: s.p256dh, auth: s.auth } },
        payload
      );
      ok++;
    } catch (e) {
      /* ⚠️ 404 and 410 mean the subscription is GONE — app deleted, phone
         wiped, permission revoked. Those are retired immediately rather
         than retried forever; every other failure is counted, because a
         push service having a bad ten minutes must not cost somebody
         their notifications permanently. */
      const code = e?.statusCode;
      if (code === 404 || code === 410) dead.push(s.id);
      else if (s.failures >= 9) dead.push(s.id);
      else await admin.from('push_subscriptions')
             .update({ failures: s.failures + 1 }).eq('id', s.id);
    }
  }));

  if (dead.length) {
    await admin.from('push_subscriptions').delete().in('id', dead);
  }
  if (ok) {
    await admin.from('push_subscriptions')
      .update({ last_ok_at: new Date().toISOString(), failures: 0 })
      .eq('user_id', n.user_id).gt('failures', 0);
  }

  return NextResponse.json({ ok: true, devices: subs.length, delivered: ok, retired: dead.length });
}
